### ISSUE TITLE
Default theme

### ISSUE THREAD

**Issue by oliviertassinari** [cssinjs/theming#24]
This issue is part of a series of feedbacks. [I been upgrading the Material-UI solution](https://github.com/callemall/material-ui/pull/7461).
Unfortunately, I had to fork the package in order to reach my goal.
Now, it's time to reconciliation.

### The issue

It would be awesome if we could be supporting a default theme.
That's something I have been implementing on Material-UI in order to reduce onboarding friction.

**Comment by kof** [comment]
@oliviertassinari please feel free to add specific code suggestions or even implement it and send a PR!

**Comment by oliviertassinari** [comment]
Here is an implementation example: https://github.com/callemall/material-ui/blob/926256d70c727b7ea6a668ac40fb3add5faf44cc/src/styles/withTheme.js#L12-L19.
