### ISSUE TITLE
Upgrade brcast to version ^3

### ISSUE THREAD

**Issue by darkowic** [cssinjs/theming#36]
Due to brcast issue - https://github.com/vesparny/brcast/issues/7

This library is used in react-jss and material-ui alpha and I'm receiving error from webpack's uglify.

@oliviertassinari @kof

**Comment by oliviertassinari** [comment]
@darkowic Material-UI isn't using theming. We are relying on brcast@3.0.1.

**Comment by darkowic** [comment]
But it's using _react-jss_ which is using _theming_ :) At least in version 1.0 beta which I'm using

**Comment by hburrows** [comment]
Upgrades to support React 16 upgrade `brcast` dependency to 3.0.1
